### ISSUE TITLE
[1.12] Various Problems in Harder Ores

### ISSUE THREAD

**Issue by Thyriel** [Draco18s/ReasonableRealism#15]
Great to see that you updated HarderOres to 1.12 ;)

But badly there's quite some bugs:

- Item names (=localization) are missing for both Harder Ores and and Ore Flowers items
- all 9 small dust > 1 big dust recipes (except sugar) create 1 small dust  (JEI doesn't even show large dusts for anything else then iron / gold / flour). So basically those recipes just destroy 8 small dusts.
- Tin is totally missing the 9 small > 1 big dust recipe
- destroying the windmill multiblock structure while there are still ores being processed destroys those ores instead dropping them
- Sifter only accepts iron / gold dust (but at least produces large dusts) > probably because of the missing large dusts.
- the packager GUI isn't displaying any item names while hovering over them in the inventory
- There's insane lag on the server (even in singleplayer): tons of "Can't keep up! Did the system time change, or is the server overloaded? Running 25182ms behind, skipping 503 tick(s)" Error messages in logfile and noticeable lag (not fps drops) when doing stuff. (e.g. taking like 5sec to change gamemode). No other mods running.

**Comment by Draco18s** [comment]
- Localization: fixed: missing pack.mcmeta file was causing lang files to be loaded under v2 instead of v3.
- Dust recipes: Fixed the 9 -> 1 issue, was inadvertently supplying the wrong output item. Tin, etc. large dusts are not supplied by Harder Ores, looking for a solution (which may be that I have to).
- Destroying the windmill: definitely a problem, kind of been a ongoing fix/break fix/break as MC updates. Unable to replicate. Inserted 8 chunks, destroyed center, got 6 chunks and 4 dust (two chunks worth). Tried again with an edge. Inserted 4 iron, then 4 gold, destroyed edge. Got 4 gold. Check on top of the mill.
- Sifter: almost certainly
- Packager: Fixed, `GuiContainer` doesn't call `renderHoveredToolTip()` during `drawScreen()`, subclasses have to override (this is dumb).
- Lag: Unknown. Fresh world?

**Comment by Thyriel** [comment]
That was quick ;) I'll test it again when it has been uploaded to curseforge.
- Dust recipes: Would be great if you could add the mod dusts too. I would really love to change a lot recipes based on these ores without mods that use them by their own.
- Destroying Windmill: I'd only tried it two times, maybe i have really overseen them. But i didn't destroy the center block, i removed one of the side blocks. Will test again in new release and let you know.
- Lag: Will make further tests in new release. Maybe trying to remove the world generation scripts or something like that to see if it fixes the lags.  It was a new world, but been playing around in it like an hour or so in it without moving around much (so there should not have been much chunk generation)

Btw something else: Could you add Ardite / Cobalt (Tinkers Construct high tier ores) to it ?

**Comment by Draco18s** [comment]
- Dust recipes I'm working on :\ Need a way to specify a recipe with output from the oredict
- Millstone: I'm willing to bet that the items jumped up to a spot you didn't see (and timed out). If you do manage to repro it fresh, try and figure out exactly how.
- It is possible that the cascading worldgen problem in COG is to blame.
- New ores: new ores take some work. I've got to find a flower or two, generate textures, and fiddle with some other things, *and* make a COG distribution for it (the **really** time consuming task).

**Comment by Draco18s** [comment]
- Dust recipes fixed: They now return the first oredict entry for the desired dust. Of course, Harder Ores doesn't supply large dusts for mod ores as typically those mods already supply one (if there is a mod-added ore that HO supports but which itself does not have a large dust, open a new issue for that; easy to fix, but I need to know what ores). In the event no item is registered under the desired oredict name, the output is empty.  HO tiny dusts will still show up in the creative inventory.
- Also changed Iron and Gold localization on tiny dust to use the word "pile" (not sure why they've been different)

**Comment by EngineOfDarkness** [comment]
>New ores: new ores take some work. I've got to find a flower or two, generate textures, and fiddle with some other things, and make a COG distribution for it (the really time consuming task).

Not sure if dumb questions, but here I go

* Is there a way I can enable all ores to spawn in the motherlode style without breaking anything expect balance?
* If the former is possible - how does the mod detect when to take action - is there something like oredict which applies it to all ores or is this configured in the XML config files? Can I somehow find out which ores are unconfigured?

Enabling all Ores for HarderOres probably means I won't see the textures change when mining ore or see any plant-based indicators, but that's fine by me.

**Comment by Draco18s** [comment]
Ok, a few things:
1. You would need to write your own distributions in an XML config file (it would go in /modules/custom and if you use the same distribution names, it will override)
2. Harder Ores and the OreDictionary are not involved
3. Enabling all ores means it enables the distributions of those ores.  They are HarderOres ore blocks so they will function just like Iron and Gold. They're just disabled because the OreDictionary doesn't see those ores as being supplied, so it skips their population. But if you want them, then sure, turn them on.

**Comment by Draco18s** [comment]
I think all issues here have been resolved, closing for now. If there's still something, feel free to open a new issue.
